/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AuthResetImport } from './routes/auth/reset'
import { Route as AuthNewVerificationImport } from './routes/auth/new-verification'
import { Route as AuthNewPasswordImport } from './routes/auth/new-password'
import { Route as AuthNewEmailImport } from './routes/auth/new-email'
import { Route as AuthenticatedSettingsImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminImport } from './routes/_authenticated/admin'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetRoute = AuthResetImport.update({
  path: '/auth/reset',
  getParentRoute: () => rootRoute,
} as any)

const AuthNewVerificationRoute = AuthNewVerificationImport.update({
  path: '/auth/new-verification',
  getParentRoute: () => rootRoute,
} as any)

const AuthNewPasswordRoute = AuthNewPasswordImport.update({
  path: '/auth/new-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthNewEmailRoute = AuthNewEmailImport.update({
  path: '/auth/new-email',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsRoute = AuthenticatedSettingsImport.update({
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAdminRoute = AuthenticatedAdminImport.update({
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/auth/new-email': {
      id: '/auth/new-email'
      path: '/auth/new-email'
      fullPath: '/auth/new-email'
      preLoaderRoute: typeof AuthNewEmailImport
      parentRoute: typeof rootRoute
    }
    '/auth/new-password': {
      id: '/auth/new-password'
      path: '/auth/new-password'
      fullPath: '/auth/new-password'
      preLoaderRoute: typeof AuthNewPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/new-verification': {
      id: '/auth/new-verification'
      path: '/auth/new-verification'
      fullPath: '/auth/new-verification'
      preLoaderRoute: typeof AuthNewVerificationImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedAdminRoute,
    AuthenticatedProfileRoute,
    AuthenticatedSettingsRoute,
  }),
  AuthNewEmailRoute,
  AuthNewPasswordRoute,
  AuthNewVerificationRoute,
  AuthResetRoute,
  AuthSignInRoute,
  AuthSignUpRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/auth/new-email",
        "/auth/new-password",
        "/auth/new-verification",
        "/auth/reset",
        "/auth/sign-in",
        "/auth/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/admin",
        "/_authenticated/profile",
        "/_authenticated/settings"
      ]
    },
    "/_authenticated/admin": {
      "filePath": "_authenticated/admin.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings.tsx",
      "parent": "/_authenticated"
    },
    "/auth/new-email": {
      "filePath": "auth/new-email.tsx"
    },
    "/auth/new-password": {
      "filePath": "auth/new-password.tsx"
    },
    "/auth/new-verification": {
      "filePath": "auth/new-verification.tsx"
    },
    "/auth/reset": {
      "filePath": "auth/reset.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
